import fs from 'node:fs/promises';
import path from 'node:path';
const root=import.meta.dirname;
const out=path.join(root,'public');
await fs.mkdir(out,{recursive:true});
const navItems=[['about','サンプルについて'],['menu','お品書き'],['ingredients','素材のこと'],['space','店内のご案内'],['news','お知らせ'],['access','店舗情報']];
const footer=(base)=>`<footer class="footer"><a class="wordmark" href="${base}"><small>鉄板と、旬と。</small>サンプル<span>TEPPAN DINING SAMPLE</span></a><div class="footer-links"><a href="${base}recruit/">採用情報</a><a href="${base}company/">会社概要</a></div><p>このサイトは架空の店舗のサンプルです。<br>写真はAIで生成したイメージです。</p><small>© 2026 SAMPLE</small><a class="to-top" href="#top" aria-label="ページの先頭へ">↑</a></footer>`;
const shell=(title,body,{base='./',page='home'}={})=>`<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}｜サンプル</title><meta name="description" content="鉄板を囲む、しあわせな時間。旬の素材を気軽に楽しむ、架空の鉄板焼き店「サンプル」のデモサイトです。"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#392a22"><link rel="icon" href="${base}assets/favicon.svg"><link rel="preload" as="image" href="${base}assets/hero-steak.webp"><link rel="stylesheet" href="${base}assets/site.css"><script src="${base}assets/site.js" defer></script></head>
<body id="top" data-page="${page}"><a class="skip" href="#main">本文へ進む</a>
<aside class="scene" aria-label="鉄板料理のイメージ"><img class="scene-image is-current" data-scene="steak" src="${base}assets/hero-steak.webp" alt="香ばしく焼いたステーキと季節野菜"><img class="scene-image" data-scene="seasonal" src="${base}assets/seasonal.webp" alt="帆立と旬野菜の鉄板料理"><img class="scene-image" data-scene="interior" src="${base}assets/interior.webp" alt="木の温もりを感じる鉄板カウンター"><div class="scene-top"><a href="${base}" class="scene-brand">サンプル<span>TEPPAN DINING</span></a><span class="scene-edition">SAVOR THE MOMENT.</span></div><div class="scene-copy"><span class="eyebrow">GOOD FOOD, GOOD COMPANY.</span><p>鉄板を囲む、<br>しあわせな時間。</p><div class="scene-bottom"><span>旬を焼く。会話がはずむ。</span><span class="scroll-hint">SCROLL <i></i></span></div></div><div class="scene-count"><b id="scene-number">01</b> / 03</div></aside>
<div class="page-column"><header class="header"><a class="header-name" href="${base}">サンプル</a><div class="header-actions"><button class="reserve" data-dialog="reserve">ご予約<span>↗</span></button><button class="menu-toggle" aria-label="メニューを開く" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><small>MENU</small></button></div></header>
<nav id="site-nav" class="site-nav" aria-label="サイトメニュー" inert><span class="eyebrow">TEPPAN DINING SAMPLE</span><div class="nav-links">${navItems.map(([id,label],i)=>`<a href="${base}#${id}"><span>0${i+1}</span>${label}<b>↗</b></a>`).join('')}</div><div class="nav-secondary"><a href="${base}recruit/">採用情報</a><a href="${base}company/">会社概要</a></div><button class="dark-button" data-dialog="reserve">ご予約について <span>↗</span></button></nav>
<main id="main">${body}</main>${footer(base)}</div>
<dialog class="dialog" aria-labelledby="dialog-title"><form method="dialog"><button class="dialog-close" aria-label="閉じる">×</button></form><span class="eyebrow">SAMPLE INFORMATION</span><h2 id="dialog-title">ご予約について</h2><div id="dialog-body"></div><form method="dialog"><button class="dark-button">閉じる</button></form></dialog>
</body></html>`;
const heading=(n,en,ja)=>`<div class="section-heading"><span class="eyebrow">${n} / ${en}</span><h2>${ja}</h2></div>`;
const dishes=[{image:'hero-steak',name:'赤身ステーキと焼き野菜',price:'2,800',desc:'表面は香ばしく、中はしっとり。塩と季節の薬味で、肉の味わいをシンプルに。'},{image:'seasonal',name:'帆立と旬野菜の鉄板焼き',price:'1,600',desc:'甘みのある帆立に、きのこと緑の野菜を添えて。仕上げのバターがふわりと香ります。'}];
const dishCards=(base='./')=>dishes.map((d,i)=>`<article class="dish"><div class="dish-image"><img src="${base}assets/${d.image}.webp" alt="${d.name}" loading="lazy" width="1536" height="1024"><span>0${i+1}</span></div><div class="dish-title"><h3>${d.name}</h3><p>¥${d.price}<small>税込</small></p></div><p class="body-copy">${d.desc}</p></article>`).join('');
const menuContent=(base='./')=>`<div class="tabs" role="tablist" aria-label="お品書きの種類"><button role="tab" id="tab-a" aria-selected="true" aria-controls="panel-a" tabindex="0">一品料理<span>À LA CARTE</span></button><button role="tab" id="tab-b" aria-selected="false" aria-controls="panel-b" tabindex="-1">コース<span>COURSE</span></button></div><div role="tabpanel" id="panel-a" aria-labelledby="tab-a">${dishCards(base)}<dl class="menu-list"><div><dt>ふんわり豚玉</dt><dd>¥980</dd></div><div><dt>ガーリックライス</dt><dd>¥780</dd></div><div><dt>季節の焼き野菜</dt><dd>¥900</dd></div><div><dt>本日のデザート</dt><dd>¥650</dd></div></dl><p class="fine">表示価格は税込・サンプル価格です。</p></div><div role="tabpanel" id="panel-b" aria-labelledby="tab-b" hidden><div class="course-photo"><img src="${base}assets/seasonal.webp" alt="旬の食材を楽しむコースのイメージ" loading="lazy"></div><span class="tag">前日までのご予約</span><h3 class="course-title">旬を味わう、おまかせコース</h3><p class="course-price">¥5,500 <small>税込 / お一人様</small></p><p class="body-copy">鉄板を囲む時間を、ゆっくりと。前菜から甘いひと皿まで、季節の味を少しずつお楽しみください。</p><ol class="course-list"><li>季節の前菜</li><li>彩り野菜のサラダ</li><li>帆立と旬野菜の鉄板焼き</li><li>赤身ステーキ</li><li>ガーリックライス</li><li>本日のデザート</li></ol><button class="text-link" data-dialog="reserve">コースのご予約について <span>↗</span></button></div>`;
const home=`<section class="hero" data-background="steak"><div class="hero-title"><span class="eyebrow">TEPPAN DINING</span><h1>サンプル</h1><p>鉄板と、旬と。</p></div><div class="hero-photo"><img src="./assets/hero-steak.webp" alt="焼き立てのステーキ" width="1536" height="1024" fetchpriority="high"><span class="hero-seal">焼きたてを、<br>すぐそばで。</span></div><div class="hero-caption"><span>おいしい時間を、ご一緒に。</span><a href="#about" aria-label="サンプルについて読む">↓</a></div></section>
<section id="about" class="section about" data-background="steak"><span class="eyebrow">HELLO, WE ARE SAMPLE.</span><div class="vertical-intro"><h2>音も、香りも。<br>ごちそうのうち。</h2><p>鉄板から届く、食欲を誘う音。<br>立ちのぼる湯気と、香ばしいかおり。<br>目の前で生まれるおいしさを、<br>気取らず、ゆっくりと。</p></div><p class="body-copy">いい素材を、ちょうどいい焼き加減で。<br>何気ない日の晩ごはんも、大切な人との一夜も。<br>サンプルは、あなたの「また来たい」をつくります。</p><div class="about-sign">SAMPLE <span>— since 2026</span></div></section>
<section id="menu" class="section menu-section" data-background="seasonal">${heading('01','MENU','お品書き')}<p class="body-copy section-lead">好きなものを、好きなだけ。<br>今日は何を焼きましょう。</p>${menuContent()}<a class="outline-button" href="./menu/">お品書きをまとめて見る <span>↗</span></a></section>
<section id="ingredients" class="section ingredients" data-background="seasonal">${heading('02','INGREDIENTS','おいしさの、もと。')}<p class="body-copy section-lead">手をかけすぎず、素材を引き立てる。<br>私たちが大切にしている、三つのこと。</p><div class="ingredient-list">${[['01','素材に合わせた、火入れ。','肉も、魚介も、野菜も。それぞれの食感と旨みが引き立つ温度を見極め、一皿ずつ丁寧に仕上げます。'],['02','その季節に、おいしいもの。','春のやわらかさ、夏のみずみずしさ、秋の香り、冬の甘み。季節の表情を、鉄板の上で楽しみます。'],['03','最後のひと口まで、心地よく。','味の重なりと食べやすさを大切に。ひと皿を囲む会話が自然にはずむ、そんな料理を目指しています。']].map(([n,t,p])=>`<details><summary><span>${n}</span><h3>${t}</h3><b aria-hidden="true">＋</b></summary><p>${p}</p></details>`).join('')}</div></section>
<section id="space" class="space" data-background="interior"><img src="./assets/interior.webp" alt="温かい照明と木のカウンターがある店内のイメージ" width="1536" height="1024" loading="lazy"><div class="section">${heading('03','OUR SPACE','ちょうどいい、距離。')}<p class="body-copy">料理を待つ時間も、楽しみのひとつ。<br>カウンター越しに交わす会話と、温かな灯り。<br>おひとりでも、気の合う人とでも。<br>肩の力を抜いてお過ごしください。</p><span class="space-label">COUNTER / TABLE</span></div></section>
<section id="news" class="section news" data-background="interior">${heading('04','JOURNAL','お知らせ')}<div class="news-list"><button data-dialog="news-open"><time datetime="2026-09-16">2026.09.16</time><span>サンプルのウェブサイトを公開しました。</span><b>↗</b></button><button data-dialog="news-menu"><time datetime="2026-09-16">2026.09.16</time><span>季節を楽しむ、おまかせコース。</span><b>↗</b></button></div></section>
<section id="access" class="section access" data-background="interior">${heading('05','INFORMATION','お店のこと。')}<dl class="info-list"><div><dt>店名</dt><dd>サンプル</dd></div><div><dt>所在地</dt><dd>北海道札幌市<br><span class="fine">架空の店舗のため住所は未設定です。</span></dd></div><div><dt>営業時間</dt><dd>17:00 — 23:00<br><span class="fine">ラストオーダー 22:00</span></dd></div><div><dt>定休日</dt><dd>水曜日</dd></div><div><dt>お席</dt><dd>カウンター・テーブル席</dd></div><div><dt>ご予約</dt><dd>サンプルのため受付しておりません</dd></div></dl><button class="dark-button" data-dialog="reserve">ご予約・お問い合わせ <span>↗</span></button><p class="fine access-note">店舗情報・メニューはすべてサンプルです。</p></section>`;
await fs.writeFile(path.join(out,'index.html'),shell('鉄板と、旬と。',home));
const pages={
 'company':`${heading('ABOUT US','COMPANY','会社概要')}<p class="body-copy section-lead">おいしい食事と、心地よい時間を。<br>街に小さな楽しみをつくるお店を目指して。</p><dl class="info-list"><div><dt>会社名</dt><dd>株式会社サンプル</dd></div><div><dt>事業内容</dt><dd>飲食店の企画・運営</dd></div><div><dt>運営店舗</dt><dd>サンプル</dd></div><div><dt>所在地</dt><dd>北海道札幌市（サンプル）</dd></div></dl><p class="fine">このページの企業・店舗情報は架空のものです。</p>`,
 'recruit':`${heading('JOIN US','RECRUIT','おいしい時間を、<br>一緒につくる。')}<img class="subpage-photo" src="../assets/interior.webp" alt="鉄板カウンターのイメージ"><p class="body-copy section-lead">料理が好き。人と話すのが好き。<br>その気持ちを大切に、ひとつずつ。<br>気持ちのいいお店を一緒につくりませんか。</p><h2 class="small-heading">募集要項</h2><dl class="info-list"><div><dt>職種</dt><dd>キッチン・ホールスタッフ</dd></div><div><dt>業務内容</dt><dd>調理補助、接客、店舗運営</dd></div><div><dt>勤務条件</dt><dd>実際の募集時にご案内します</dd></div><div><dt>応募受付</dt><dd>現在は募集しておりません</dd></div></dl><button class="dark-button" data-dialog="recruit">採用について <span>↗</span></button><p class="fine">サンプルの採用ページです。応募情報の送信は行いません。</p>`,
 'menu':`${heading('À LA CARTE / COURSE','MENU','お品書き')}<p class="body-copy section-lead">焼きたての一皿を、気軽に。<br>料理とコースをご紹介します。</p>${menuContent('../')}`
};
for(const [name,content] of Object.entries(pages)){await fs.mkdir(path.join(out,name),{recursive:true});await fs.writeFile(path.join(out,name,'index.html'),shell(name==='company'?'会社概要':name==='recruit'?'採用情報':'お品書き',`<section class="section subpage" data-background="${name==='menu'?'seasonal':'interior'}"><a class="back-link" href="../">← トップへ</a>${content}</section>`,{base:'../',page:name}));}
await fs.writeFile(path.join(out,'.nojekyll'),'');
console.log('Built 4 original static pages into public/.');
